# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-17 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_restaurantlocation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantlocation',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
